### ISSUE TITLE
[WANT] 홈화면에서 발생하는 오류 

### ISSUE THREAD

**Issue by jmlee119** [1-screeningHumanity/TMT-FE#46]
## 요청 내용
<img width="271" alt="image" src="https://github.com/screeningHumanity/TMT-FE/assets/68285285/f8849ae8-ed07-4e23-b35a-f97bc4116b15">. 

- [ ] 홈 화면에서의 이미지 생성 오류
- [ ] 홈 화면에 footer 추가 요청

**Comment by sw-devr** [comment]
PR 받으시면 수정되어있을겁니다 
피드백 감사합니다 ~
